# version: '3'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: thwala-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Tt@19990423(#eden-minnie!)
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    restart: always
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "Tt@19990423(#eden-minnie!)" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thwala-app
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
    restart: always
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=ThwalaAttorneys;User Id=sa;Password=Tt@19990423(#eden-minnie!);TrustServerCertificate=True;MultipleActiveResultSets=true
      - ASPNETCORE_ENVIRONMENT=Production
      - EmailSettings__SmtpServer=smtp.gmail.com
      - EmailSettings__SmtpPort=587
      - EmailSettings__SmtpUsername=thwalathembinkosi16@gmail.com
      - EmailSettings__SmtpPassword=ekwcbpvixdxvhqms
      - EmailSettings__FromEmail=thwalathembinkosi16@gmail.com
      - EmailSettings__FromName=Thwala Attorneys
      - EmailSettings__LawyerEmail=thwalathembinkosi16@gmail.com
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local